package org.com.pangolin.dominio.parcela.estrategias;

public enum OrdemAmortizacaoEnum {
    PRIMEIRO_JUROS,
    PRIMEIRO_MULTA,
    PRIMEIRO_TAXA,
    PRIMEIRO_VALOR_FIXO,
    PRIMEIRO_DESCONTO,
    PRIMEIRO_OUTROS,
    PRIMEIRO_MORA_CONTABIL,
    PRIMEIRO_MORA_JUDICIAL,
    PRIMEIRO_MORA_CONTRATUAL,
    PRIMEIRO_CORRECAO_MONETARIA,
    PRIMEIRO_PRINCIPAL_INCORPORADO,
    PRIMEIRO_PRINCIPAL;
}
