package org.com.pangolin.dominio.parcela.componentes;

public enum TipoComponente {
    PRINCIPAL, JUROS, JUROS_MORA, MULTA, TAXA,VALOR_FIXO, DESCONTO,VALOR_CONTRATUAL_PARCELA, OUTROS, MORA_CONTABIL, MORA_JUDICIAL, MORA_CONTRATUAL, CORRECAO_MONETARIA;
}
